apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: music-library
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/0xSirel/Music-Library

  destinations:
    - server: https://kubernetes.default.svc
      namespace: music-library
    - server: https://kubernetes.default.svc
      namespace: metallb-system

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
