apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: music-library
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: music-library
    server: https://kubernetes.default.svc
  - name: in-cluster
    namespace: metallb-system
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
