apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.kubernetesResources.networkPolicy }}
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: mongo
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.appLabel }}
    ports:
    - port: {{ .Values.mongo.port }}
      protocol: TCP
  policyTypes:
  - Ingress
  - Egress
