name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install dependencies
      run: make init

    - name: Lint
      run: make lint-check

    - name: Run tests
      run: make test
      env:
        DISCOGS_TOKEN: ${{ secrets.DISCOGS_TOKEN }}
        
    - name: Install buld package
      run:  pip install build
      
    - name: Build
      run: python -m build
